# The project is a top-level crate *as well* as a workspace.
# The `pueue_lib` crate lives in the `lib` folder.
# The following is the shared configuration for both pueue and its lib
[workspace]
members = ["lib"]

[workspace.package]
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
license = "MIT"
edition = "2021"
rust-version = "1.63"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
serde = "1"
serde_json = "1"
serde_derive = "1"
snap = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time", "io-std"] }


# ------------------------
# Start of the actual "pueue" config.
# ------------------------
[package]
name = "pueue"
version = "2.1.0"
description = "A cli tool for managing long running shell commands."
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "pueue"
path = "client/main.rs"

[[bin]]
name = "pueued"
path = "daemon/main.rs"

# Split the daemon logic in a lib and bin crate.
# Using a lib allows us to do proper integration testing.
[lib]
name = "pueue_daemon_lib"
path = "daemon/lib.rs"

[dependencies]
pueue-lib = { version = "0.21.0", path = "lib" }

anyhow = "1"
chrono-english = "0.1"
clap = { version = "4", features = ["derive", "cargo"] }
clap_complete = "4"
comfy-table = "6"
crossbeam-channel = "0.5"
crossterm = "0.25"
ctrlc = { version = "3", features = ["termination"] }
handlebars = "4"
pest = "2"
pest_derive = "2"
shell-escape = "0.1"
simplelog = { version = "0.12", default-features = false }
tempfile = "3"

chrono = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
snap = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
better-panic = "0.3"
pretty_assertions = "1"
rstest = "0.15"
serde_yaml = "0.9"
similar-asserts = "1"

# Test specific dev-dependencies
[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
nix = "0.25"
whoami = "1"
procfs = { version = "0.14", default-features = false }
