# The project is a top-level crate *as well* as a workspace.
# The `pueue_lib` crate lives in the `lib` folder.
# The following is the shared configuration for both pueue and its lib
[workspace]
members = ["pueue", "pueue_lib"]
resolver = "2"

[workspace.package]
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
# Chrono version is hard pinned to a specific version.
# See https://github.com/Nukesor/pueue/issues/534
chrono = { version = "0.4", features = ["serde"] }
command-group = "5"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
snap = "1.1"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.36", features = ["rt-multi-thread", "time", "io-std"] }
handlebars = "5.1"
anyhow = "1"
better-panic = "0.3"
pretty_assertions = "1"

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
