[package]
name = "pueue"
description = "A cli tool for managing long running shell commands."
version = "2.0.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
documentation = "https://docs.rs/pueue/"
license = "MIT"
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "README.md"
rust-version = "1.56"
edition = "2021"

[badges]
maintenance = { status="actively-developed" }

[workspace]
members = ["lib"]

[[bin]]
name = "pueue"
path = "client/main.rs"

# Split the daemon logic in a lib and bin crate.
# The bin crate uses the lib to for all logic, but using a lib allows
# us to do proper integration testing.
[lib]
name = "pueue_daemon_lib"
path = "daemon/lib.rs"

[[bin]]
name = "pueued"
path = "daemon/main.rs"

[dependencies]
pueue-lib = { version="0.19", path="lib" }

anyhow = "1"
chrono = { version="0.4", features=["serde"] }
chrono-english = "0.1"
shell-escape = "0.1"
tempfile = "3"

crossbeam-channel = "0.5"
tokio = { version="1", features=["rt-multi-thread", "time", "io-std"] }
snap = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"

log = "0.4"
simplelog = { version="0.10", default-features=false }
clap = "=3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
crossterm = "0.22"
comfy-table = "5"

handlebars = "4"
ctrlc = { version="3", features=["termination"] }

# Windows
[target.'cfg(windows)'.dependencies]
winapi = { version="0.3", features=[
  "tlhelp32",
  "handleapi",
  "processthreadsapi",
  "minwindef",
  "impl-default",
] }

# Unix
[target.'cfg(not(windows))'.dependencies]
nix = "0.23"
whoami = "1"

# Linux / Freebsd
[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
procfs = { version="0.11", default-features=false }

[dev-dependencies]
assert_cmd = "2"
anyhow = "1"
better-panic = "0.2"
pretty_assertions = "1"
rstest = "0.11"
