# The project is a top-level crate *as well* as a workspace.
# The `pueue_lib` crate lives in the `lib` folder.
# The following is the shared configuration for both pueue and its lib
[workspace]
members = ["pueue", "pueue_lib"]

[workspace.package]
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
license = "MIT"
edition = "2021"
rust-version = "1.67"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
command-group = "2"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0"
snap = "1.1"
strum = "0.25"
strum_macros = "0.25"
tokio = { version = "1.32", features = ["rt-multi-thread", "time", "io-std"] }

# Dev dependencies
anyhow = "1"
better-panic = "0.3"
pretty_assertions = "1"

[profile.release]
lto = "thin"
