[package]
name = "pueue"
description = "A cli tool for managing long running shell commands."
version = "0.9.1-alpha.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
documentation = "https://docs.rs/pueue/"
license = "MIT"
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "README.md"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "pueue"
path = "client/main.rs"

[[bin]]
name = "pueued"
path = "daemon/main.rs"

[lib]
name = "pueue"
path = "shared/lib.rs"

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes", "std"] }
async-trait = "0.1"
dirs = "3"
chrono = { version = "^0.4", features = ["serde"] }
chrono-english = "^0.1.0"
ctrlc = { version = "3", features = ["termination"] }
rand = "^0.7"
strum = "^0.20"
strum_macros = "^0.20"
handlebars = "3"

bytes = "^0.6"
byteorder = "^1"
snap = "1"
serde = "^1.0"
bincode = "^1.2"
serde_json = "^1.0"
serde_yaml = "^0.8"
serde_derive = "^1.0"

log = "0.4"
config = { version = "^0.10", default-features = false, features = ["yaml"] }
simplelog = { version = "0.8", default-features = false }
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
crossterm = "^0.18"
comfy-table= "^1"
tempfile = "^3"

[target.'cfg(not(windows))'.dependencies]
users = "^0.11"
nix = "^0.19"

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
procfs = { version = "0.9", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
psutil = "^3"

[build-dependencies]
version_check = "^0.9"

[dev-dependencies]
proptest = "^0.10"
